bindings:
  MoveForward: KeyW
  ToggleFly: F1
  Chat: Enter
  Map: KeyM
  MoveRight: KeyD
  Crouch: ControlLeft
  Hotbar6: Digit6
  ToggleMenu: Escape
  Jump: Space
  Hotbar5: Digit5
  Hotbar8: Digit8
  ToggleInventory: KeyI
  MoveLeft: KeyA
  Interact: KeyE
  Screenshot: F12
  Hotbar1: Digit1
  Hotbar2: Digit2
  MoveBackward: KeyS
  Hotbar3: Digit3
  Hotbar7: Digit7
  ToggleSnapMode: KeyX
  Sprint: ShiftLeft
  ToggleFog: KeyP
  ToggleBuildingMode: KeyB
  RotatePiece: KeyR
  Hotbar9: Digit9
  Hotbar4: Digit4
  ToggleDebug: F3
