export const REQUIRED_COUNTERS = [
  "frame_ms_p95",
  "frame_ms_p99",
  "frame_ms_avg",
  "target_visible_m",
  "stream_ready_frame",
  "draw_calls",
  "total_scene_tris",
  "terrain_draw_calls",
  "rendered_terrain_tris",
  "far_shell_enabled",
  "far_shell_tris",
  "far_shell_radius_m",
  "far_shell_grid_res",
  "far_shell_rebuild_restarts",
  "streamer_far_shell_ownership_ok",
  "ring_boundary_holes",
  "live_clod_gap_holes",
  "clod_far_gap_holes",
  "live_clod_overlap_cells",
  "clod_far_overlap_cells",
  "priority_owner_overlap_cells",
  "priority_unowned_cells",
  "clod_parent_coverage_violations",
  "missing_live_chunks_in_required_radius",
  "missing_clod_pages_in_required_radius",
  "camera_to_clod_center_m",
  "camera_to_far_shell_center_m",
  "far_shell_inner_minus_clod_radius_m",
  "streamer_live_radius_m",
  "streamer_clod_radius_m",
  "ownership_oracle_ms",
  "residency_missing_live",
  "residency_missing_clod",
  "horizon_hole_ratio",
  "far_clipmap_enabled",
  "far_clipmap_visible",
  "far_clipmap_active_rings",
  "far_clipmap_ready_tiles",
  "far_clipmap_pending_tiles",
  "far_clipmap_rebuilt_this_frame",
  "far_clipmap_source_ready",
  "far_clipmap_build_ms",
  "far_clipmap_build_ms_total",
  "far_clipmap_vertices_built_this_frame",
  "far_clipmap_triangles_built_this_frame",
  "far_clipmap_fallback_samples_this_frame",
  "far_clipmap_fallback_samples_total",
  "far_clipmap_exception_samples_this_frame",
  "far_clipmap_exception_samples_total",
  "far_clipmap_inner_radius_m",
  "far_clipmap_outer_radius_m",
  "far_clipmap_gpu_owned_cells",
  "far_clipmap_gpu_ownership_holes",
  "far_clipmap_owned_cells",
  "far_clipmap_unowned_cells",
  "far_clipmap_ownership_holes",
  "far_clipmap_priority_overlap_cells",
  "owner_far_clipmap_cells",
  "owner_clod_refinement_cells",
  "owner_live_cells",
  "far_summary_tiles_required",
  "far_summary_tiles_ready",
  "far_summary_tiles_missing",
  "far_summary_tiles_stale",
  "far_summary_procedural_fallback_samples",
  "far_summary_lower_ring_fallback_samples",
  "far_summary_conservative_fallback_samples",
  "far_summary_stale_restores",
  "far_summary_builds_discarded",
  "far_summary_probe_fallbacks",
  "far_summary_probe_height_error_max_m",
  "live_bubble_required_pages",
  "live_bubble_ready_pages",
  "live_bubble_building_pages",
  "live_bubble_failed_pages",
  "live_bubble_valid_empty_pages",
  "live_bubble_gpu_retry_pages",
  "live_bubble_gpu_retries_total",
  "live_bubble_gpu_failures_total",
  "live_bubble_built_this_frame",
  "live_bubble_built_total",
  "live_bubble_ms",
  "live_bubble_evictions",
  "live_bubble_evictions_total",
  "live_bubble_cached_pages",
  "live_bubble_streamed_collider_pages",
  "live_bubble_collider_registrations",
  "live_bubble_collider_removals",
  "live_bubble_gpu_dispatch_budget",
  "live_bubble_max_inflight_chunks",
  "live_bubble_pending_chunks",
  "live_bubble_inflight_chunks",
  "live_bubble_ready_visual_pages",
  "live_bubble_avg_chunk_ms",
  "live_bubble_slowest_page_ms",
  "live_bubble_visual_required_pages",
  "live_bubble_visual_ready_pages",
  "live_bubble_collider_required_pages",
  "live_bubble_collider_ready_pages",
  "live_bubble_collider_skipped_pages",
  "live_bubble_probe_active",
  "live_bubble_probe_built_total",
  "live_bubble_probe_evictions_total",
  "live_bubble_probe_collider_removals_total",
  "live_clod_stream_required_pages",
  "live_clod_stream_cached_pages",
  "live_clod_stream_built_this_frame",
  "live_clod_stream_built_total",
  "live_clod_stream_failed_pages",
  "live_clod_stream_evictions",
  "live_clod_stream_evictions_total",
  "live_clod_stream_radius_m",
  "live_clod_stream_build_ms",
  "live_clod_stream_pending_pages",
  "live_clod_stream_build_budget",
  "live_clod_stream_inflight_batches",
  "live_clod_stream_max_inflight_batches",
  "live_clod_stream_apply_queue_pages",
  "live_clod_stream_active_root_pages",
  "live_clod_stream_max_cached_pages",
  "live_clod_stream_safety_cache_capacity_ok",
  "live_clod_stream_safety_required_pages",
  "live_clod_stream_safety_ready_pages",
  "live_clod_stream_safety_pending_pages",
  "live_clod_stream_safety_inflight_pages",
  "live_clod_stream_refinement_pending_pages",
  "live_clod_stream_refinement_inflight_pages",
  "live_clod_stream_parent_coverage_violations",
  "live_clod_stream_ready_pages",
  "live_clod_stream_scheduled_pages_this_frame",
  "live_clod_stream_apply_pages_this_frame",
  "live_clod_stream_apply_pages_total",
  "live_clod_stream_apply_ms",
  "live_clod_stream_stale_discards",
  "live_clod_stream_stale_discards_total",
  "live_clod_stream_worker_build_ms",
  "live_clod_stream_worker_transfer_bytes",
  "live_clod_stream_probe_active",
  "live_clod_stream_probe_requested_pages_total",
  "live_clod_stream_probe_apply_pages_total",
  "live_clod_stream_probe_evictions_total",
  "live_clod_stream_probe_stale_discards_total",
  "live_clod_stream_out_of_world_edits_supported",
  "vegetation_ring_unbounded",
  "vegetation_ring_center_x",
  "vegetation_ring_center_z",
  "vegetation_grass_center_x",
  "vegetation_grass_center_z",
  "vegetation_ring_distance_to_grass_m",
  "infinite_hydrology_outside_sample_valid",
  "infinite_hydrology_outside_body_mask",
  "infinite_hydrology_outside_depth_m",
  "infinite_hydrology_nonrepeat_delta",
  "infinite_hydrology_nonrepeat_ok",
  "infinite_hydrology_camera_outside_startup",
] as const;

export type RequiredCounter = typeof REQUIRED_COUNTERS[number];

export interface ThresholdRule {
  key: RequiredCounter;
  label: string;
  pass: (value: number, values: Readonly<Record<string, number>>) => boolean;
}

const finiteNonNegative = (value: number): boolean => Number.isFinite(value) && value >= 0;
const inactiveOrPositive = (activeKey: RequiredCounter) => (value: number, values: Readonly<Record<string, number>>): boolean =>
  finiteNonNegative(value) && (values[activeKey] !== 1 || value > 0);
const clodMissingCoveredOrReady = (value: number, values: Readonly<Record<string, number>>): boolean =>
  value === 0 || ((values["stream_ready_frame"] ?? -1) < 0 && (values["clod_parent_coverage_violations"] ?? 1) === 0);
const streamProbeEvictionOrNoPressure = (value: number, values: Readonly<Record<string, number>>): boolean => {
  if (!finiteNonNegative(value)) return false;
  if (values["live_clod_stream_probe_active"] !== 1) return true;
  const staleDiscards = values["live_clod_stream_probe_stale_discards_total"] ?? 0;
  if (value + staleDiscards > 0) return true;
  const cached = values["live_clod_stream_cached_pages"] ?? 0;
  const maxCached = values["live_clod_stream_max_cached_pages"] ?? 0;
  return finiteNonNegative(cached) && finiteNonNegative(maxCached) && cached < maxCached;
};

const FRAME_TIME_COUNTERS = new Set<RequiredCounter>([
  "frame_ms_p95",
  "frame_ms_p99",
  "frame_ms_avg",
]);

const ORACLE_COUNTERS = new Set<RequiredCounter>([
  "ring_boundary_holes",
  "live_clod_gap_holes",
  "clod_far_gap_holes",
  "live_clod_overlap_cells",
  "clod_far_overlap_cells",
  "priority_owner_overlap_cells",
  "priority_unowned_cells",
  "clod_parent_coverage_violations",
  "missing_live_chunks_in_required_radius",
  "missing_clod_pages_in_required_radius",
  "camera_to_clod_center_m",
  "camera_to_far_shell_center_m",
  "far_shell_inner_minus_clod_radius_m",
  "streamer_clod_radius_m",
  "ownership_oracle_ms",
  "residency_missing_live",
  "residency_missing_clod",
  "horizon_hole_ratio",
  "far_clipmap_owned_cells",
  "far_clipmap_unowned_cells",
  "far_clipmap_ownership_holes",
  "far_clipmap_priority_overlap_cells",
  "owner_far_clipmap_cells",
  "owner_clod_refinement_cells",
  "owner_live_cells",
]);

export const THRESHOLD_RULES: ThresholdRule[] = [
  { key: "frame_ms_p95", label: "must be finite, >= 0 and <= 8", pass: (value) => Number.isFinite(value) && value >= 0 && value <= 8 },
  { key: "frame_ms_p99", label: "must be >= 0", pass: (value) => value >= 0 },
  { key: "stream_ready_frame", label: "must be finite and >= 0", pass: (value) => Number.isFinite(value) && value >= 0 },
  { key: "streamer_far_shell_ownership_ok", label: "must equal 1", pass: (value) => value === 1 },
  { key: "ring_boundary_holes", label: "must equal 0", pass: (value) => value === 0 },
  { key: "live_clod_gap_holes", label: "must equal 0", pass: (value) => value === 0 },
  { key: "clod_far_gap_holes", label: "must equal 0", pass: (value) => value === 0 },
  { key: "live_clod_overlap_cells", label: "must equal 0", pass: (value) => value === 0 },
  { key: "clod_far_overlap_cells", label: "must equal 0", pass: (value) => value === 0 },
  { key: "priority_owner_overlap_cells", label: "must equal 0", pass: (value) => value === 0 },
  { key: "priority_unowned_cells", label: "must equal 0", pass: (value) => value === 0 },
  { key: "clod_parent_coverage_violations", label: "must equal 0", pass: (value) => value === 0 },
  { key: "missing_live_chunks_in_required_radius", label: "must equal 0", pass: (value) => value === 0 },
  { key: "missing_clod_pages_in_required_radius", label: "must equal 0, or be parent-covered before stream_ready_frame", pass: clodMissingCoveredOrReady },
  { key: "residency_missing_live", label: "must equal 0", pass: (value) => value === 0 },
  { key: "residency_missing_clod", label: "must equal 0, or be parent-covered before stream_ready_frame", pass: clodMissingCoveredOrReady },
  { key: "camera_to_clod_center_m", label: "must be <= 1", pass: (value) => value <= 1 },
  { key: "camera_to_far_shell_center_m", label: "must be <= 1", pass: (value) => value <= 1 },
  { key: "far_shell_inner_minus_clod_radius_m", label: "may overlap CLOD but must be finite", pass: (value) => Number.isFinite(value) },
  { key: "streamer_clod_radius_m", label: "must be finite and > 0", pass: (value) => Number.isFinite(value) && value > 0 },
  { key: "horizon_hole_ratio", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_enabled", label: "must equal 1", pass: (value) => value === 1 },
  { key: "far_clipmap_visible", label: "must equal 1", pass: (value) => value === 1 },
  { key: "far_clipmap_active_rings", label: "must be > 0", pass: (value) => value > 0 },
  { key: "far_clipmap_ready_tiles", label: "must cover active rings", pass: (value, values) => value >= (values["far_clipmap_active_rings"] ?? Number.POSITIVE_INFINITY) },
  { key: "far_clipmap_pending_tiles", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_rebuilt_this_frame", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "far_clipmap_source_ready", label: "must equal 1", pass: (value) => value === 1 },
  { key: "far_clipmap_build_ms", label: "must be finite, >= 0 and <= 6", pass: (value) => Number.isFinite(value) && value >= 0 && value <= 6 },
  { key: "far_clipmap_build_ms_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "far_clipmap_vertices_built_this_frame", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "far_clipmap_triangles_built_this_frame", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "far_clipmap_fallback_samples_this_frame", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_fallback_samples_total", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_exception_samples_this_frame", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_exception_samples_total", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_inner_radius_m", label: "must be finite and > live radius", pass: (value, values) => Number.isFinite(value) && value > (values["streamer_live_radius_m"] ?? 0) },
  { key: "far_clipmap_outer_radius_m", label: "must be >= target visible radius", pass: (value, values) => value >= (values["target_visible_m"] ?? Number.POSITIVE_INFINITY) },
  { key: "far_clipmap_gpu_owned_cells", label: "must be > 0", pass: (value) => value > 0 },
  { key: "far_clipmap_gpu_ownership_holes", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_owned_cells", label: "must be > 0", pass: (value) => value > 0 },
  { key: "far_clipmap_unowned_cells", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_ownership_holes", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_clipmap_priority_overlap_cells", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "owner_far_clipmap_cells", label: "must be > 0", pass: (value) => value > 0 },
  { key: "owner_clod_refinement_cells", label: "must be > 0", pass: (value) => value > 0 },
  { key: "owner_live_cells", label: "must be > 0", pass: (value) => value > 0 },
  { key: "far_summary_tiles_missing", label: "must equal 0 after warmup", pass: (value) => value === 0 },
  { key: "far_summary_procedural_fallback_samples", label: "must equal 0 after warmup", pass: (value) => value === 0 },
  { key: "far_summary_lower_ring_fallback_samples", label: "must equal 0 after warmup", pass: (value) => value === 0 },
  { key: "far_summary_conservative_fallback_samples", label: "must equal 0 after warmup", pass: (value) => value === 0 },
  { key: "far_summary_builds_discarded", label: "must equal 0", pass: (value) => value === 0 },
  { key: "far_summary_probe_fallbacks", label: "must equal 0 after warmup", pass: (value) => value === 0 },
  { key: "live_bubble_required_pages", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_ready_pages", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_building_pages", label: "must equal 0 at steady state", pass: (value) => value === 0 },
  { key: "live_bubble_failed_pages", label: "must equal 0", pass: (value) => value === 0 },
  { key: "live_bubble_valid_empty_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_gpu_retry_pages", label: "must equal 0 at steady state", pass: (value) => value === 0 },
  { key: "live_bubble_gpu_retries_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_gpu_failures_total", label: "must equal 0", pass: (value) => value === 0 },
  { key: "live_bubble_ms", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_built_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_evictions_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_probe_built_total", label: "must be > 0 when the movement probe is active", pass: inactiveOrPositive("live_bubble_probe_active") },
  { key: "live_bubble_probe_evictions_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  {
    key: "live_bubble_probe_collider_removals_total",
    label: "must be finite and remove colliders if route-owned live-bubble pages evicted",
    pass: (value, values) => finiteNonNegative(value) && ((values["live_bubble_probe_evictions_total"] ?? 0) <= 0 || value > 0),
  },
  { key: "live_bubble_streamed_collider_pages", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_collider_registrations", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_gpu_dispatch_budget", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_max_inflight_chunks", label: "must be finite and > 0", pass: (value) => Number.isFinite(value) && value > 0 },
  { key: "live_bubble_pending_chunks", label: "must equal 0 at steady state", pass: (value) => value === 0 },
  { key: "live_bubble_inflight_chunks", label: "must equal 0 at steady state", pass: (value) => value === 0 },
  { key: "live_bubble_ready_visual_pages", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_avg_chunk_ms", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_slowest_page_ms", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_visual_required_pages", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_visual_ready_pages", label: "must be > 0", pass: (value) => value > 0 },
  { key: "live_bubble_collider_required_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_collider_ready_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_bubble_collider_skipped_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_required_pages", label: "must be > 0", pass: (value) => value > 0 },
  {
    key: "live_clod_stream_ready_pages",
    label: "must be > 0 when worker stream roots are required and enabled",
    pass: (value, values) => value > 0 || values["live_clod_stream_required_pages"] === 0,
  },
  { key: "live_clod_stream_cached_pages", label: "must be finite and >= ready roots", pass: (value, values) => finiteNonNegative(value) && value >= (values["live_clod_stream_ready_pages"] ?? 0) },
  { key: "live_clod_stream_max_inflight_batches", label: "must be finite and > 0", pass: (value) => Number.isFinite(value) && value > 0 },
  { key: "live_clod_stream_inflight_batches", label: "must be <= live_clod_stream_max_inflight_batches", pass: (value, values) => value <= (values["live_clod_stream_max_inflight_batches"] ?? -1) },
  { key: "live_clod_stream_apply_queue_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_active_root_pages", label: "must equal ready pages", pass: (value, values) => value === (values["live_clod_stream_ready_pages"] ?? -1) },
  { key: "live_clod_stream_max_cached_pages", label: "must be finite and > 0", pass: (value) => Number.isFinite(value) && value > 0 },
  {
    key: "live_clod_stream_safety_cache_capacity_ok",
    label: "must equal 1 when streamed roots are required",
    pass: (value, values) => value === 1 || values["live_clod_stream_required_pages"] === 0,
  },
  { key: "live_clod_stream_safety_required_pages", label: "must be > 0 when streamed roots are required", pass: (value, values) => value > 0 || values["live_clod_stream_required_pages"] === 0 },
  {
    key: "live_clod_stream_safety_required_pages",
    label: "must be <= live_clod_stream_max_cached_pages",
    pass: (value, values) => value <= (values["live_clod_stream_max_cached_pages"] ?? -1) || values["live_clod_stream_required_pages"] === 0,
  },
  { key: "live_clod_stream_safety_ready_pages", label: "must cover all required safety pages", pass: (value, values) => value >= (values["live_clod_stream_safety_required_pages"] ?? 0) },
  { key: "live_clod_stream_safety_pending_pages", label: "must equal 0 after safety warmup", pass: (value) => value === 0 },
  { key: "live_clod_stream_safety_inflight_pages", label: "must equal 0 after safety warmup", pass: (value) => value === 0 },
  { key: "live_clod_stream_refinement_pending_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_refinement_inflight_pages", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_parent_coverage_violations", label: "must equal 0", pass: (value) => value === 0 },
  { key: "live_clod_stream_radius_m", label: "must be >= streamer_clod_radius_m", pass: (value, values) => value >= (values["streamer_clod_radius_m"] ?? Number.POSITIVE_INFINITY) },
  { key: "live_clod_stream_failed_pages", label: "must equal 0", pass: (value) => value === 0 },
  { key: "live_clod_stream_build_ms", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_built_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_evictions_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_apply_pages_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_stale_discards_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_scheduled_pages_this_frame", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_apply_ms", label: "must be finite, >= 0 and <= 2", pass: (value) => Number.isFinite(value) && value >= 0 && value <= 2 },
  { key: "live_clod_stream_worker_build_ms", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_worker_transfer_bytes", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_probe_requested_pages_total", label: "must be > 0 when the movement probe is active", pass: inactiveOrPositive("live_clod_stream_probe_active") },
  { key: "live_clod_stream_probe_apply_pages_total", label: "must be > 0 when the movement probe is active", pass: inactiveOrPositive("live_clod_stream_probe_active") },
  {
    key: "live_clod_stream_probe_evictions_total",
    label: "must exercise eviction/stale-discard only when the stream cache reaches capacity",
    pass: streamProbeEvictionOrNoPressure,
  },
  { key: "live_clod_stream_probe_stale_discards_total", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "live_clod_stream_out_of_world_edits_supported", label: "must equal 0 until out-of-world dig edits are implemented", pass: (value) => value === 0 },
  { key: "vegetation_ring_unbounded", label: "must equal 1 for infinite islands", pass: (value) => value === 1 },
  { key: "vegetation_ring_distance_to_grass_m", label: "must be <= 1", pass: (value) => value <= 1 },
  { key: "infinite_hydrology_outside_sample_valid", label: "must equal 1", pass: (value) => value === 1 },
  { key: "infinite_hydrology_outside_body_mask", label: "must be finite and >= 0", pass: finiteNonNegative },
  { key: "infinite_hydrology_outside_depth_m", label: "must be finite", pass: (value) => Number.isFinite(value) },
  { key: "infinite_hydrology_nonrepeat_delta", label: "must be > 0.01 outside startup world", pass: (value) => value > 0.01 },
  { key: "infinite_hydrology_nonrepeat_ok", label: "must equal 1", pass: (value) => value === 1 },
  { key: "infinite_hydrology_camera_outside_startup", label: "must equal 1 for infinite acceptance scenes", pass: (value) => value === 1 },
];

export interface ThresholdEvaluation {
  passed: boolean;
  failures: string[];
  values: Record<string, number>;
}

export function evaluateThresholds(stats: Record<string, unknown>): ThresholdEvaluation {
  const values: Record<string, number> = {};
  const failures: string[] = [];
  for (const key of REQUIRED_COUNTERS) {
    const raw = stats[key];
    const value = typeof raw === "number" ? raw : Number(raw);
    values[key] = value;
    if (!Number.isFinite(value)) failures.push(`${key}=missing/non-finite`);
  }
  for (const rule of THRESHOLD_RULES) {
    const value = values[rule.key];
    if (!Number.isFinite(value)) continue;
    if (!rule.pass(value, values)) failures.push(`${rule.key}=${value} (${rule.label})`);
  }
  if ((values["stream_ready_frame"] ?? -1) < 0) {
    for (const key of ORACLE_COUNTERS) {
      const value = values[key];
      if (value !== undefined && value !== 0 && key !== "camera_to_clod_center_m" && key !== "camera_to_far_shell_center_m" && key !== "far_shell_inner_minus_clod_radius_m" && key !== "ownership_oracle_ms" && key !== "streamer_clod_radius_m") {
        failures.push(`${key}=${value} before stream_ready_frame`);
      }
    }
  }
  const p95 = values["frame_ms_p95"];
  if (p95 !== undefined && p95 > 8) {
    failures.push(`frame_ms_p95=${p95.toFixed(2)} > 8`);
  }
  return { passed: failures.length === 0, failures, values };
}
