import { DEFAULT_CAUSTICS_CONFIG } from "./causticsConfig.js";
import { cloneHydrologyConfig } from "./hydrologyConfig.js";
import { deriveDefaultWaterBodyPresets } from "./water_body_presets.js";
import type { WaterConfig, WaterVisualConfig } from "./water_config_types.js";
import { WATER_DEBUG_MODES } from "./water_config_types.js";

const DEFAULT_WATER_CELLS_PER_LEVEL = 96;
const DEFAULT_WATER_CELL_SIZES = [2.0, 4.0, 8.0, 16.0, 32.0];
const DEFAULT_WATER_REFRACTION_STRENGTH = 0.0;

export const DEFAULT_WATER_VISUAL: WaterVisualConfig = {
  shallowColor: [0.00, 0.32, 0.55],
  deepColor: [0.012, 0.06, 0.17],
  foamColor: [0.90, 0.95, 0.96],
  alpha: 0.90,
  rippleCycle: 0.07,
  fresnelPower: 5.0,
  rippleAmp: 0.32,
  rippleSpeed: 0.52,
  rippleScaleA: 0.16,
  rippleScaleB: 0.105,
  rippleStrengthA: 0.24,
  rippleStrengthB: 0.16,
  rippleLoopDistance: 22.0,
  lakeBreeze: [0.20, 0.07],
  shoreFoamStart: 0.03,
  shoreFoamEnd: 0.16,
  maxDepthForColor: 5.0,
  foam: {
    noiseScale: 0.075,
    shoreStrength: 0.52,
    riverStrength: 0.38,
    speedStart: 0.25,
    speedEnd: 1.0,
    dropStart: 0.5,
    dropEnd: 2.0,
    shoreDistanceStart: 0.0,
    shoreDistanceEnd: 2.5,
    detailFadeStartM: 120.0,
    detailFadeEndM: 320.0,
  },
  fresnel: {
    base: 0.065,
    power: 4.2,
    normalFlatten: 0.92,
  },
  color: {
    depthScale: 5.0,
    turbidity: 0.10,
  },
  bodies: deriveDefaultWaterBodyPresets({
    shallowColor: [0.00, 0.32, 0.55],
    deepColor: [0.012, 0.06, 0.17],
    depthScale: 5.0,
    turbidity: 0.10,
  }),
  glacialMurkiness: {
    enabled: false,
    lakeStrength: 1.0,
    riverStrength: 0.75,
    absorptionMultiplier: [1.55, 1.30, 1.15],
    turbidityAdd: 0.28,
    reflectionDampingMin: 0.68,
  },
  rockFlour: {
    enabled: false,
    lakeStrength: 1.0,
    riverStrength: 0.82,
    lakeColor: [0.07, 0.38, 0.36],
    riverColor: [0.08, 0.43, 0.39],
    shallowBlend: 0.62,
    deepBlend: 0.28,
    scatterExtinction: 0.42,
    scatterStrength: 0.85,
    scatterAmbient: 0.72,
  },
  glitter: {
    enabled: true,
    tightExponent: 384,
    tightGain: 1.15,
    broadExponent: 96,
    broadGain: 0.28,
    lowSunGain: 0.35,
  },
  refraction: {
    enabled: false,
    strength: DEFAULT_WATER_REFRACTION_STRENGTH,
    depthValidationBias: 0.02,
    absorptionR: 0.42,
    absorptionG: 0.135,
    absorptionB: 0.095,
    turbidityStrength: 0.032,
    maxThickness: 8.0,
  },
  reflection: {
    mode: "fake",
    ssrEnabled: false,
    maxSteps: 18,
    stepScale: 0.09,
    edgeFadeStart: 1.0,
    edgeFadeEnd: 0.82,
    skyFallbackStrength: 0.78,
    terrainFallbackStrength: 0.12,
    clipmapTiers: {
      enabled: false,
      fullQualityMaxCellSizeM: 4.0,
      midQualityMaxCellSizeM: 16.0,
      midMaxSteps: 6,
    },
    farSummary: {
      enabled: false,
      sourceResolution: 65,
      sourceSpanM: 1024,
      sourceSnapM: 64,
      sourceBuildCellsPerFrame: 512,
      maxSteps: 6,
      startDistanceM: 16,
      maxDistanceM: 320,
      stepGrowth: 1.8,
      thicknessM: 18,
      terrainStrength: 0.52,
      propStrength: 0.72,
    },
  },
  depthWrite: false,
};

export const DEFAULT_WATER_CONFIG: WaterConfig = {
  enabled: true,
  source: "hydrology",
  cellsPerLevel: DEFAULT_WATER_CELLS_PER_LEVEL,
  cellSizes: DEFAULT_WATER_CELL_SIZES,
  snapCells: 2,
  staticTopology: true,
  drySentinelDepth: 2.0,
  fakeBodies: {
    carveTerrain: true,
    lakes: [
      { center: [0, 0], centerNorm: [0.50, 0.50], radius: [42, 30], levelOffset: 1.2 },
      { center: [0, 0], centerNorm: [0.25, 0.72], radius: [32, 24], levelOffset: 1.0 },
    ],
    rivers: [
      {
        points: [],
        pointsNorm: [[0.16, 0.34], [0.30, 0.42], [0.48, 0.48], [0.66, 0.57], [0.84, 0.66]],
        width: 9.0,
        levelOffset: 0.8,
        downstreamDrop: 3.0,
      },
    ],
  },
  hydrology: cloneHydrologyConfig(),
  visual: { ...DEFAULT_WATER_VISUAL },
  caustics: { ...DEFAULT_CAUSTICS_CONFIG },
  debug: { mode: WATER_DEBUG_MODES.final, clipmapTint: false, wireframe: false },
};
