import { beforeEach, describe, expect, it, vi } from "vitest";
import { TERRAIN_SOURCE_VERSION } from "../../cache/terrainSource.js";
import { DEFAULT_ISLAND_SHAPE_CONFIG } from "../../world_source/island_shape.js";

const mocks = vi.hoisted(() => ({
  consume: vi.fn(),
  loadSavedWorldStartup: vi.fn(),
  emitAudio: vi.fn(),
}));

vi.mock("../../audio/index.js", () => ({ emitAudio: mocks.emitAudio }));
vi.mock("../../project/voxel_project_archive.js", () => ({
  consumeStagedVoxelProjectImport: mocks.consume,
  isCurrentVoxelProjectManifest: (manifest: { schemaVersion?: number }) => manifest.schemaVersion === 4,
}));
vi.mock("./save_world_startup.js", () => ({ loadSavedWorldStartup: mocks.loadSavedWorldStartup }));

import { loadStagedProjectImport } from "./project_import_startup.js";

function dom() {
  return {
    buildProgress: { hidden: true } as HTMLElement,
    buildProgressPhase: { textContent: "" } as HTMLElement,
    buildProgressPercent: { textContent: "" } as HTMLElement,
    buildProgressBar: { value: 0 } as HTMLProgressElement,
    info: { textContent: "" } as HTMLElement,
  };
}

function currentContents(generatorVersion = TERRAIN_SOURCE_VERSION) {
  return {
    manifest: {
      schemaVersion: 4,
      world: {
        scene: "infinite-islands",
        generatorVersion,
        terrainField: {
          seed: 73,
          seaLevel: 21,
          islandShape: {
            ...DEFAULT_ISLAND_SHAPE_CONFIG,
            enabled: true,
            oceanRim: true,
            seed: 73,
            seaLevel: 21,
            worldRadiusM: 12_000,
            spacingM: 1700,
            radiusM: 620,
            blendM: 280,
          },
        },
      },
    },
    customTextures: new Map(),
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  vi.stubGlobal("location", { pathname: "/", hash: "" });
  vi.stubGlobal("history", { replaceState: vi.fn() });
});

describe("project import startup", () => {
  it("restores the complete query-visible world identity", async () => {
    mocks.consume.mockResolvedValue(currentContents());
    const params = new URLSearchParams("import=token&seed=1&scene=default&hud=1");

    const result = await loadStagedProjectImport(params, dom());

    expect(result).not.toBeNull();
    expect(params.get("import")).toBeNull();
    expect(params.get("scene")).toBe("infinite-islands");
    expect(params.get("seed")).toBe("73");
    expect(params.get("seaLevel")).toBe("21");
    expect(params.get("islands")).toBe("1");
    expect(params.get("oceanRim")).toBe("1");
    expect(params.get("worldRadius")).toBe("12000");
    expect(params.get("islandSpacing")).toBe("1700");
    expect(params.get("islandRadius")).toBe("620");
    expect(params.get("islandBlend")).toBe("280");
    expect(params.get("hud")).toBe("1");
    expect(mocks.emitAudio).toHaveBeenCalledWith("project.import.success");
  });

  it("rejects a project generated by an incompatible terrain version", async () => {
    mocks.consume.mockResolvedValue(currentContents("future-generator"));
    const params = new URLSearchParams("import=token&seed=1");
    const elements = dom();

    const result = await loadStagedProjectImport(params, elements);

    expect(result).toBeNull();
    expect(elements.info.textContent).toMatch(/incompatible/i);
    expect(params.get("seed")).toBe("1");
    expect(params.get("import")).toBeNull();
    expect(mocks.emitAudio).toHaveBeenCalledWith("project.import.error");
  });

  it("keeps explicit URL identity for a legacy v3 archive", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    mocks.consume.mockResolvedValue({ manifest: { schemaVersion: 3 }, customTextures: new Map() });
    const params = new URLSearchParams("import=token&seed=9&scene=continent");

    const result = await loadStagedProjectImport(params, dom());

    expect(result).not.toBeNull();
    expect(params.get("seed")).toBe("9");
    expect(params.get("scene")).toBe("continent");
    expect(warn).toHaveBeenCalledOnce();
    warn.mockRestore();
  });
});
