import type { TreeSettings } from "./tree_config_types.js";

export const DEFAULT_TREE_PLACEMENT_SETTINGS = {
  patchSizeM: 64,
  patchGridRadius: 7,
  seedJitter: 0.41,
  maxPatchBuildsPerFrame: 6,
  terrainSamplePaddingM: 3,
  terrainHeightOffsetM: 0,
  minGroundNormalY: 0.62,
  minSpacingM: 3.4,
  maxSlopeNormalY: 0.58,
  underwaterRejectMarginM: 0.18,
  minWaterDistanceM: 1.5,
  slopeDensityPower: 1.7,
  materialWeightPower: 1.25,
  patchCullMarginM: 96,
  terrainOcclusionReject: true,
  terrainOcclusionPaddingM: 4,
  terrainOcclusionStepM: 16,
  terrainOcclusionMaxDistanceM: 384,
  terrainOcclusionHeightBiasM: 5,
};

export const DEFAULT_TREE_LOD_SETTINGS = {
  nearDistanceM: 90,
  midDistanceM: 240,
  farDistanceM: 900,
  impostorDistanceM: 480,
  impostorFraction: 1.0,
  hysteresisM: 8,
  crossfadeEnabled: true,
  crossfadeBandM: 24,
  ditherEnabled: true,
  shadowsMaxLod: "near" as const,
  budgets: {
    nearMaxVertices: 260_000,
    midMaxVertices: 90_000,
    farMaxVertices: 40_000,
    impostorMaxVertices: 240,
  },
};

export const DEFAULT_TREE_IMPOSTOR_SETTINGS = {
  enabled: true,
  bakeOnStart: true,
  fallbackToPlaceholder: false,
  swapOnBake: true,
  sourceLod: "near" as const,
  resolutionPx: 256,
  octahedralGridSize: 8,
  atlasColumns: 8,
  atlasRows: 8,
  paddingPx: 4,
  normalDepthPacking: true,
  alphaCutoff: 0.38,
  maxBakePerFrame: 1,
};

export const DEFAULT_TREE_FOLIAGE_SETTINGS = {
  cardCountNear: 96,
  cardCountMid: 36,
  cardCountFar: 12,
  cardWidthM: 1.2,
  cardHeightM: 1.8,
  cardSizeVariation: 0.35,
  clusterSpreadM: 2.7,
  crownFlattening: 0.18,
};

export const DEFAULT_TREE_WIND_SETTINGS = {
  enabled: true,
  strength: 0.25,
  speed: 0.65,
  gustStrength: 0.18,
  gustScaleM: 96,
  direction: [0.6, 0.8] as [number, number],
};

export const DEFAULT_TREE_RENDER_SETTINGS = {
  alphaTest: 0.42,
  castShadows: true,
  receiveShadows: true,
  depthPrepass: true,
  debugColorByLod: false,
  farCheapMaterial: true,
};

export const DEFAULT_TREE_GPU_SETTINGS = {
  enabled: true,
  clusterSizeM: 128,
  maxClustersPerFrame: 256,
  visibleClusterPaddingM: 96,
  terrainVisibility: {
    enabled: true,
    maxDistanceM: 4096,
    heightMarginM: 6,
    crownHeightM: 14,
  },
};

export const DEFAULT_TREE_ECOLOGY_SETTINGS = {
  enabled: true,
  density: {
    baseDensity: 0.76,
    forestNoiseScaleM: 450,
    forestNoiseStrength: 0.62,
    clearingNoiseScaleM: 160,
    clearingThreshold: 0.68,
    clearingSoftness: 0.12,
    edgeSoftnessM: 18,
  },
  terrain: {
    lowlandHeightM: 16,
    highlandHeightM: 180,
    heightFadeM: 28,
    slopeFadeStartY: 0.72,
    slopeFadeEndY: 0.48,
    materialWeightPower: 1.35,
  },
  clustering: {
    clusterScaleM: 115,
    clusterStrength: 0.55,
    clusterThreshold: 0.52,
    minSpacingJitter: 0.35,
  },
  age: {
    youngProbability: 0.22,
    oldProbability: 0.18,
    scaleYoung: 0.56,
    scaleMature: 1.0,
    scaleOld: 1.22,
    scaleVariation: 0.32,
  },
  speciesZones: {
    oak: {
      enabled: true,
      lowlandWeight: 0.55,
      highlandWeight: 0.35,
      forestEdgeWeight: 0.45,
      clearingWeight: 0.28,
      heightPreference: "any" as const,
    },
    pine: {
      enabled: true,
      lowlandWeight: 0.25,
      highlandWeight: 0.75,
      forestEdgeWeight: 0.32,
      clearingWeight: 0.18,
      heightPreference: "high" as const,
    },
    birch: {
      enabled: true,
      lowlandWeight: 0.5,
      highlandWeight: 0.4,
      forestEdgeWeight: 0.85,
      clearingWeight: 0.65,
      heightPreference: "any" as const,
    },
  },
};

export const DEFAULT_TREE_SETTINGS: TreeSettings = {
  enabled: true,
  seed: 4317,
  distanceM: 1800,
  refreshDistanceM: 48,
  maxNewPatchesPerFrame: 8,
  maxInstances: 120_000,
  species: {
    oak: {
      enabled: true,
      weight: 0.45,
      minHeightM: 10,
      maxHeightM: 21,
      trunkHeightM: 4.2,
      trunkRadiusM: 0.36,
      crownRadiusM: 4.5,
      morphology: {
        trunkBend: 0.12,
        trunkTaper: 0.72,
        branchLevels: 4,
        primaryBranchCount: 8,
        secondaryBranchCount: 18,
        branchSpread: 0.85,
        branchUpSweep: 0.38,
        branchLength: 1.0,
        crownFlattening: 0.18,
        crownIrregularity: 0.35,
        leafClusterCount: 32,
        leafCardCount: 96,
      },
    },
    pine: {
      enabled: true,
      weight: 0.35,
      minHeightM: 14,
      maxHeightM: 30,
      trunkHeightM: 6.5,
      trunkRadiusM: 0.32,
      crownRadiusM: 3.2,
      morphology: {
        trunkBend: 0.05,
        trunkTaper: 0.86,
        branchLevels: 7,
        primaryBranchCount: 7,
        secondaryBranchCount: 10,
        branchSpread: 0.62,
        branchUpSweep: 0.62,
        branchLength: 0.82,
        crownFlattening: 0.05,
        crownIrregularity: 0.18,
        leafClusterCount: 44,
        leafCardCount: 82,
      },
    },
    birch: {
      enabled: true,
      weight: 0.2,
      minHeightM: 8,
      maxHeightM: 18,
      trunkHeightM: 4.8,
      trunkRadiusM: 0.22,
      crownRadiusM: 3.4,
      morphology: {
        trunkBend: 0.18,
        trunkTaper: 0.78,
        branchLevels: 5,
        primaryBranchCount: 6,
        secondaryBranchCount: 12,
        branchSpread: 0.72,
        branchUpSweep: 0.5,
        branchLength: 0.75,
        crownFlattening: 0.16,
        crownIrregularity: 0.42,
        leafClusterCount: 28,
        leafCardCount: 70,
      },
    },
  },
  placement: DEFAULT_TREE_PLACEMENT_SETTINGS,
  lod: DEFAULT_TREE_LOD_SETTINGS,
  impostors: DEFAULT_TREE_IMPOSTOR_SETTINGS,
  foliage: DEFAULT_TREE_FOLIAGE_SETTINGS,
  wind: { ...DEFAULT_TREE_WIND_SETTINGS, direction: [...DEFAULT_TREE_WIND_SETTINGS.direction] },
  render: DEFAULT_TREE_RENDER_SETTINGS,
  gpu: DEFAULT_TREE_GPU_SETTINGS,
  ecology: DEFAULT_TREE_ECOLOGY_SETTINGS,
};

export function cloneTreeSettings(source: TreeSettings = DEFAULT_TREE_SETTINGS): TreeSettings {
  return structuredClone(source);
}
