export const TREE_IMPOSTOR_MIP_ALPHA_TEST = 0.32;
export const TREE_IMPOSTOR_MIP_BYTES_PER_PIXEL = 4;
export const TREE_IMPOSTOR_MIP_NORMAL_BYTE_CENTER = 127.5;
export const TREE_IMPOSTOR_MIP_MAX_COVERAGE_SCALE = 8;
export const TREE_IMPOSTOR_MIP_COVERAGE_SEARCH_STEPS = 16;
export const TREE_IMPOSTOR_MIP_DEFAULT_OPERATIONS = 1024;
