$ErrorActionPreference = "Stop"

# Complete CLOD parity QA runner for Windows PowerShell.
#
# This runner supersets scripts/run-clod-full-parity-suite.ps1 once the later
# diagnostics patches are applied. It exports every CLOD telemetry stream, runs
# every CLOD guard, and writes the aggregated Markdown/JSON report.

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Resolve-Path (Join-Path $ScriptDir "..")
Set-Location $RootDir

$RunId = if ($env:CLOD_PARITY_RUN_ID) { $env:CLOD_PARITY_RUN_ID } else { (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ") }
$RunDir = if ($env:CLOD_PARITY_RUN_DIR) { $env:CLOD_PARITY_RUN_DIR } else { "bench-runs/clod-complete-$RunId" }
$PlanScene = if ($env:CLOD_PARITY_PLAN_SCENE) { $env:CLOD_PARITY_PLAN_SCENE } else { "bench/scenes/terrain/clod-edit-stress.toml" }
$BenchScene = if ($env:CLOD_PARITY_BENCH_SCENE) { $env:CLOD_PARITY_BENCH_SCENE } else { "bench/scenes/terrain/clod-parity-stress.toml" }

$EventsCsv = Join-Path $RunDir "clod-edit-events.csv"
$CutFreezeCsv = Join-Path $RunDir "clod-cut-freeze.csv"
$BorderLockCsv = Join-Path $RunDir "clod-border-locks.csv"
$TopologyCsv = Join-Path $RunDir "clod-topology.csv"
$SimplifyCsv = Join-Path $RunDir "clod-simplify.csv"
$WeldCsv = Join-Path $RunDir "clod-weld.csv"

Write-Host "[CLOD complete QA] run dir: $RunDir"
Write-Host "[CLOD complete QA] validating edit plan schema: $PlanScene"
cargo run --bin clod_edit_plan_guard -- $PlanScene

Write-Host "[CLOD complete QA] exporting scripted edit events: $EventsCsv"
cargo run --bin clod_edit_events_export -- $PlanScene --out $EventsCsv

Write-Host "[CLOD complete QA] guarding scripted edit events"
scripts/guard-clod-edit-events.ps1 -Csv $EventsCsv

$env:VOXEL_CLOD_STATS_CSV_PATH = $SelectionCsv
$env:VOXEL_CLOD_REBUILD_CSV = "1"
$env:VOXEL_CLOD_REBUILD_CSV_PATH = $RebuildCsv
$env:VOXEL_CLOD_CROSSFADE_BRIDGE = "1"
$env:VOXEL_CLOD_CROSSFADE_MATERIAL = "1"
$env:VOXEL_CLOD_CROSSFADE_STATS_CSV = "1"
$env:VOXEL_CLOD_CROSSFADE_STATS_CSV_PATH = $CrossfadeCsv
$env:VOXEL_CLOD_CUT_FREEZE_CSV = "1"
$env:VOXEL_CLOD_CUT_FREEZE_CSV_PATH = $CutFreezeCsv
$env:VOXEL_CLOD_BORDER_LOCK_CSV = "1"
$env:VOXEL_CLOD_BORDER_LOCK_CSV_PATH = $BorderLockCsv
$env:VOXEL_CLOD_TOPOLOGY_CSV = "1"
$env:VOXEL_CLOD_TOPOLOGY_CSV_PATH = $TopologyCsv
$env:VOXEL_CLOD_SIMPLIFY_CSV = "1"
$env:VOXEL_CLOD_SIMPLIFY_CSV_PATH = $SimplifyCsv
$env:VOXEL_CLOD_WELD_CSV = "1"
$env:VOXEL_CLOD_WELD_CSV_PATH = $WeldCsv
cargo run --release -- --bench $BenchScene

Write-Host "[CLOD complete QA] guarding selection stats"
$SelectionConfig = if ($env:CLOD_STATS_GUARD_CONFIG) { $env:CLOD_STATS_GUARD_CONFIG } else { "assets/config/clod_stats_guard.toml" }
cargo run --bin clod_stats_guard -- $SelectionCsv --config $SelectionConfig

Write-Host "[CLOD complete QA] guarding rebuild stats"
$RebuildConfig = if ($env:CLOD_REBUILD_GUARD_CONFIG) { $env:CLOD_REBUILD_GUARD_CONFIG } else { "assets/config/clod_rebuild_guard.toml" }
cargo run --bin clod_rebuild_guard -- $RebuildCsv --config $RebuildConfig

Write-Host "[CLOD complete QA] guarding crossfade stats"
scripts/guard-clod-crossfade.ps1 -Csv $CrossfadeCsv

Write-Host "[CLOD complete QA] guarding cut-freeze stats"
scripts/guard-clod-cut-freeze.ps1 -Csv $CutFreezeCsv

Write-Host "[CLOD complete QA] guarding visual parity integration"
scripts/guard-clod-visual-parity.ps1 -SelectionCsv $SelectionCsv -CrossfadeCsv $CrossfadeCsv -CutFreezeCsv $CutFreezeCsv

Write-Host "[CLOD complete QA] guarding border locks"
scripts/guard-clod-border-locks.ps1 -Csv $BorderLockCsv

Write-Host "[CLOD complete QA] guarding topology"
scripts/guard-clod-topology.ps1 -Csv $TopologyCsv

Write-Host "[CLOD complete QA] guarding simplification"
scripts/guard-clod-simplify.ps1 -Csv $SimplifyCsv

Write-Host "[CLOD complete QA] guarding welds"
scripts/guard-clod-welds.ps1 -Csv $WeldCsv

if ($env:VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD -eq "1") {
    Write-Host "[CLOD complete QA] guarding edit plan against rebuild telemetry"
    scripts/guard-clod-edit-rebuild.ps1 -PlanCsv $PlanCsv -RebuildCsv $RebuildCsv
} else {
    Write-Host "[CLOD complete QA] skipped edit-vs-rebuild guard; set VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD=1 after scripted edit execution is wired."
}

Write-Host "[CLOD complete QA] writing aggregate report"
scripts/report-clod-qa.ps1 -RunDir $RunDir

$Readme = @"
# CLOD complete QA run $RunId

Generated by ``scripts/run-clod-complete-qa.ps1``.

## Inputs

- plan scene: ``$PlanScene``
- bench scene: ``$BenchScene``

- ``clod-edit-events.csv``
- ``clod-cut-freeze.csv``
- ``clod-border-locks.csv``
- ``clod-topology.csv``
- ``clod-simplify.csv``
- ``clod-weld.csv``
- ``clod-qa-report.md``
- ``clod-qa-report.json``

``clod_edit_rebuild_guard`` is skipped by default until scripted edit execution
is connected to the bench runtime. Enable it with:

````powershell
`$env:VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD="1"; scripts/run-clod-complete-qa.ps1
````
"@
Set-Content -Path (Join-Path $RunDir "README.md") -Value $Readme

Write-Host "[CLOD complete QA] complete: $RunDir"
