#!/usr/bin/env bash
set -euo pipefail

# Complete CLOD parity QA runner.
#
# This runner supersets scripts/run-clod-full-parity-suite.sh once the later
# diagnostics patches are applied. It keeps the older runner intact and adds a
# single command that exports every CLOD telemetry stream, runs every CLOD guard,
# and writes the aggregated Markdown/JSON report.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_ID="${CLOD_PARITY_RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_DIR="${CLOD_PARITY_RUN_DIR:-bench-runs/clod-complete-${RUN_ID}}"
PLAN_SCENE="${CLOD_PARITY_PLAN_SCENE:-bench/scenes/terrain/clod-edit-stress.toml}"
BENCH_SCENE="${CLOD_PARITY_BENCH_SCENE:-bench/scenes/terrain/clod-parity-stress.toml}"

EVENTS_CSV="$RUN_DIR/clod-edit-events.csv"
CUT_FREEZE_CSV="$RUN_DIR/clod-cut-freeze.csv"
BORDER_LOCK_CSV="$RUN_DIR/clod-border-locks.csv"
TOPOLOGY_CSV="$RUN_DIR/clod-topology.csv"
SIMPLIFY_CSV="$RUN_DIR/clod-simplify.csv"
WELD_CSV="$RUN_DIR/clod-weld.csv"
PLAN_CSV="$RUN_DIR/clod-edit-plan.csv"
SELECTION_CSV="$RUN_DIR/clod-selection-runtime.csv"
REBUILD_CSV="$RUN_DIR/clod-rebuild-observer.csv"
CROSSFADE_CSV="$RUN_DIR/clod-crossfade-runtime.csv"

printf '[CLOD complete QA] run dir: %s
' "$RUN_DIR"
printf '[CLOD complete QA] validating edit plan schema: %s
' "$PLAN_SCENE"
cargo run --bin clod_edit_plan_guard -- "$PLAN_SCENE"

printf '[CLOD complete QA] exporting edit dirty plan: %s
' "$PLAN_CSV"
cargo run --bin clod_edit_plan_export -- "$PLAN_SCENE" --out "$PLAN_CSV"
printf '[CLOD complete QA] exporting scripted edit events: %s
' "$EVENTS_CSV"
cargo run --bin clod_edit_events_export -- "$PLAN_SCENE" --out "$EVENTS_CSV"

printf '[CLOD complete QA] guarding scripted edit events
'
scripts/guard-clod-edit-events.sh "$EVENTS_CSV"


printf '[CLOD complete QA] guarding selection stats
'
cargo run --bin clod_stats_guard -- "$SELECTION_CSV" --config "${CLOD_STATS_GUARD_CONFIG:-assets/config/clod_stats_guard.toml}"

printf '[CLOD complete QA] guarding rebuild stats
'
cargo run --bin clod_rebuild_guard -- "$REBUILD_CSV" --config "${CLOD_REBUILD_GUARD_CONFIG:-assets/config/clod_rebuild_guard.toml}"

printf '[CLOD complete QA] guarding crossfade stats
'
scripts/guard-clod-crossfade.sh "$CROSSFADE_CSV"

printf '[CLOD complete QA] guarding cut-freeze stats
'
scripts/guard-clod-cut-freeze.sh "$CUT_FREEZE_CSV"

printf '[CLOD complete QA] guarding visual parity integration
'
scripts/guard-clod-visual-parity.sh "$SELECTION_CSV" "$CROSSFADE_CSV" "$CUT_FREEZE_CSV"

printf '[CLOD complete QA] guarding border locks
'
scripts/guard-clod-border-locks.sh "$BORDER_LOCK_CSV"

printf '[CLOD complete QA] guarding topology
'
scripts/guard-clod-topology.sh "$TOPOLOGY_CSV"

printf '[CLOD complete QA] guarding simplification
'
scripts/guard-clod-simplify.sh "$SIMPLIFY_CSV"

printf '[CLOD complete QA] guarding welds
'
scripts/guard-clod-welds.sh "$WELD_CSV"

if [[ "${VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD:-0}" == "1" ]]; then
  printf '[CLOD complete QA] guarding edit plan against rebuild telemetry
'
  scripts/guard-clod-edit-rebuild.sh "$PLAN_CSV" "$REBUILD_CSV"
else
  printf '[CLOD complete QA] skipped edit-vs-rebuild guard; set VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD=1 after scripted edit execution is wired.
'
fi

printf '[CLOD complete QA] writing aggregate report
'
scripts/report-clod-qa.sh "$RUN_DIR"

cat > "$RUN_DIR/README.md" <<EOF_README
# CLOD complete QA run ${RUN_ID}

Generated by \`scripts/run-clod-complete-qa.sh\`.

## Inputs

- plan scene: \`${PLAN_SCENE}\`
- bench scene: \`${BENCH_SCENE}\`

## Artifacts

- \`clod-edit-plan.csv\`
- \`clod-selection-runtime.csv\`
- \`clod-rebuild-observer.csv\`
- \`clod-crossfade-runtime.csv\`
- \`clod-cut-freeze.csv\`
- \`clod-border-locks.csv\`
- \`clod-topology.csv\`
- \`clod-simplify.csv\`
- \`clod-weld.csv\`
- \`clod-qa-report.md\`
- \`clod-qa-report.json\`

\`clod_edit_rebuild_guard\` is skipped by default until scripted edit execution
is connected to the bench runtime. Enable it with:

\`\`\`bash
VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD=1 scripts/run-clod-complete-qa.sh
\`\`\`
EOF_README

printf '[CLOD complete QA] complete: %s
' "$RUN_DIR"
