$ErrorActionPreference = "Stop"

# End-to-end CLOD parity QA runner for Windows PowerShell.

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Resolve-Path (Join-Path $ScriptDir "..")
Set-Location $RootDir

$RunId = if ($env:CLOD_PARITY_RUN_ID) { $env:CLOD_PARITY_RUN_ID } else { (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ") }
$RunDir = if ($env:CLOD_PARITY_RUN_DIR) { $env:CLOD_PARITY_RUN_DIR } else { "bench-runs/clod-parity-$RunId" }
$PlanScene = if ($env:CLOD_PARITY_PLAN_SCENE) { $env:CLOD_PARITY_PLAN_SCENE } else { "bench/scenes/terrain/clod-edit-stress.toml" }
$BenchScene = if ($env:CLOD_PARITY_BENCH_SCENE) { $env:CLOD_PARITY_BENCH_SCENE } else { "bench/scenes/terrain/clod-parity-stress.toml" }
$BorderLockConfig = if ($env:CLOD_BORDER_LOCK_GUARD_CONFIG) { $env:CLOD_BORDER_LOCK_GUARD_CONFIG } else { "assets/config/clod_border_lock_guard.toml" }

$PlanCsv = Join-Path $RunDir "clod-edit-plan.csv"
$BorderLockCsv = Join-Path $RunDir "clod-border-locks.csv"

Write-Host "[CLOD QA] run dir: $RunDir"
Write-Host "[CLOD QA] validating edit plan schema: $PlanScene"
cargo run --bin clod_edit_plan_guard -- $PlanScene

Write-Host "[CLOD QA] exporting edit dirty plan: $PlanCsv"
cargo run --bin clod_edit_plan_export -- $PlanScene $PlanCsv

Write-Host "[CLOD QA] running live-LOD CLOD bench: $BenchScene"
$env:CLOD_PAGES = "1"
$env:VOXEL_CLOD_STATS_CSV = "1"
$env:VOXEL_CLOD_STATS_CSV_PATH = $SelectionCsv
$env:VOXEL_CLOD_REBUILD_CSV = "1"
$env:VOXEL_CLOD_REBUILD_CSV_PATH = $RebuildCsv
$env:VOXEL_CLOD_CROSSFADE_BRIDGE = "1"
$env:VOXEL_CLOD_BORDER_LOCK_CSV = "1"
$env:VOXEL_CLOD_BORDER_LOCK_CSV_PATH = $BorderLockCsv

Write-Host "[CLOD QA] guarding selection stats"
cargo run --bin clod_stats_guard -- --config $SelectionConfig $SelectionCsv

Write-Host "[CLOD QA] guarding rebuild stats"
cargo run --bin clod_rebuild_guard -- --config $RebuildConfig $RebuildCsv


Write-Host "[CLOD QA] guarding border-lock stats"
cargo run --bin clod_border_lock_guard -- $BorderLockCsv $BorderLockConfig

if ($env:VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD -eq "1") {
    Write-Host "[CLOD QA] guarding edit plan against rebuild telemetry"
    cargo run --bin clod_edit_rebuild_guard -- $PlanCsv $RebuildCsv
} else {
    Write-Host "[CLOD QA] skipped edit-vs-rebuild guard; set VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD=1 after scripted edit execution is wired."
}

$Readme = @"
# CLOD parity run $RunId

Generated by ``scripts/run-clod-full-parity-suite.ps1``.

- plan scene: ``$PlanScene``
- bench scene: ``$BenchScene``
- edit plan CSV: ``clod-edit-plan.csv``
- border-lock CSV: ``clod-border-locks.csv``

````powershell
`$env:VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD="1"; scripts/run-clod-full-parity-suite.ps1
````
"@
Set-Content -Path (Join-Path $RunDir "README.md") -Value $Readme

Write-Host "[CLOD QA] complete: $RunDir"
