#!/usr/bin/env bash
set -euo pipefail

# End-to-end CLOD parity QA runner.
#
# Runs the PoC-parity checks that are safe before scripted edit execution is
# wired into the Bevy bench runtime:
#
# 3. run a live-LOD CLOD bench with selection, rebuild, crossfade, and border-lock CSVs;
# 4. run the selection, rebuild, crossfade, and border-lock guards;

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_ID="${CLOD_PARITY_RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_DIR="${CLOD_PARITY_RUN_DIR:-bench-runs/clod-parity-${RUN_ID}}"
PLAN_SCENE="${CLOD_PARITY_PLAN_SCENE:-bench/scenes/terrain/clod-edit-stress.toml}"
BENCH_SCENE="${CLOD_PARITY_BENCH_SCENE:-bench/scenes/terrain/clod-parity-stress.toml}"
CONFIG_BORDER_LOCK="${CLOD_BORDER_LOCK_GUARD_CONFIG:-assets/config/clod_border_lock_guard.toml}"

mkdir -p "$RUN_DIR"

PLAN_CSV="$RUN_DIR/clod-edit-plan.csv"
BORDER_LOCK_CSV="$RUN_DIR/clod-border-locks.csv"

printf '[CLOD QA] run dir: %s\n' "$RUN_DIR"
printf '[CLOD QA] validating edit plan schema: %s\n' "$PLAN_SCENE"
cargo run --bin clod_edit_plan_guard -- "$PLAN_SCENE"

printf '[CLOD QA] exporting edit dirty plan: %s\n' "$PLAN_CSV"
cargo run --bin clod_edit_plan_export -- "$PLAN_SCENE" "$PLAN_CSV"

printf '[CLOD QA] running live-LOD CLOD bench: %s\n' "$BENCH_SCENE"
CLOD_PAGES=1 \
VOXEL_CLOD_STATS_CSV=1 \
VOXEL_CLOD_STATS_CSV_PATH="$SELECTION_CSV" \
VOXEL_CLOD_REBUILD_CSV=1 \
VOXEL_CLOD_REBUILD_CSV_PATH="$REBUILD_CSV" \
VOXEL_CLOD_CROSSFADE_BRIDGE=1 \
VOXEL_CLOD_BORDER_LOCK_CSV=1 \
VOXEL_CLOD_BORDER_LOCK_CSV_PATH="$BORDER_LOCK_CSV" \

printf '[CLOD QA] guarding selection stats\n'
cargo run --bin clod_stats_guard -- --config "$CONFIG_SELECTION" "$SELECTION_CSV"

printf '[CLOD QA] guarding rebuild stats\n'
cargo run --bin clod_rebuild_guard -- --config "$CONFIG_REBUILD" "$REBUILD_CSV"


printf '[CLOD QA] guarding border-lock stats\n'
cargo run --bin clod_border_lock_guard -- "$BORDER_LOCK_CSV" "$CONFIG_BORDER_LOCK"

if [[ "${VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD:-0}" == "1" ]]; then
  printf '[CLOD QA] guarding edit plan against rebuild telemetry\n'
  cargo run --bin clod_edit_rebuild_guard -- "$PLAN_CSV" "$REBUILD_CSV"
else
  printf '[CLOD QA] skipped edit-vs-rebuild guard; set VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD=1 after scripted edit execution is wired.\n'
fi

cat > "$RUN_DIR/README.md" <<EOF_README
# CLOD parity run ${RUN_ID}

Generated by \`scripts/run-clod-full-parity-suite.sh\`.

- plan scene: \`${PLAN_SCENE}\`
- bench scene: \`${BENCH_SCENE}\`
- edit plan CSV: \`clod-edit-plan.csv\`
- border-lock CSV: \`clod-border-locks.csv\`
is connected to the bench runtime. Enable it with:

\`\`\`bash
VOXEL_CLOD_RUN_EDIT_REBUILD_GUARD=1 scripts/run-clod-full-parity-suite.sh
\`\`\`
EOF_README

printf '[CLOD QA] complete: %s\n' "$RUN_DIR"
