import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { load } from "js-yaml";
import type { LegacyIdMapEntry, UnifiedQaRegistry, UnifiedQaScene } from "./schema.js";
import { parseScene } from "./manifest_scene.js";
import { exact, identifier, listValue, objectValue, positiveInteger, targetValue, textValue } from "./manifest_value.js";
import { assertSafeRepositoryPath, assertUnique, verifyOptionalSha256 } from "./validation.js";

export interface ManifestPaths { visual: string; performance: string; legacyMap?: string }
export function loadUnifiedRegistry(paths: ManifestPaths): UnifiedQaRegistry {
  const visual = parseRoot(paths.visual, "visual_regression", true); const performance = parseRoot(paths.performance, "performance_regression", false); const scenes = [...visual.scenes, ...performance.scenes]; assertUnique(scenes.map(({ id }) => id), "unified QA scene id"); validatePaths(scenes, resolve(dirname(paths.visual), "../..")); if (paths.legacyMap) validateLegacyMap(parseLegacyMap(paths.legacyMap), scenes); return { schemaVersion: 1, baselineVersion: visual.baselineVersion, outputRoot: visual.outputRoot, scenes };
}
export function selectScenes(registry: UnifiedQaRegistry, tags: readonly string[] = [], ids: readonly string[] = []): UnifiedQaScene[] { const selected = registry.scenes.filter((scene) => scene.enabled && (ids.length === 0 || ids.includes(scene.id)) && tags.every((tag) => scene.tags.includes(tag))); if (!selected.length) throw new Error(`no enabled QA scenes matched tags=[${tags}] ids=[${ids}]`); return selected; }
export function reproductionCommand(scene: UnifiedQaScene): string { return scene.target === "bevy" ? `cargo run --bin qa -- --manifest-validate-only --scene ${scene.id}` : `npm --prefix tools/clod-poc run visual:regression -- --scene ${scene.id}`; }
function parseRoot(path: string, name: string, visual: boolean): { baselineVersion: number; outputRoot: string; scenes: UnifiedQaScene[] } { const file = objectValue(readYaml(path), path, [name]); const rootPath = `${path}.${name}`; const keys = visual ? ["schema_version", "baseline_version", "default_target", "output_root", "scenes"] : ["schema_version", "default_target", "output_root", "scenes"]; const value = objectValue(file[name], rootPath, keys); exact(value.schema_version, 1, `${rootPath}.schema_version`); targetValue(value.default_target, `${rootPath}.default_target`); return { baselineVersion: visual ? positiveInteger(value.baseline_version, `${rootPath}.baseline_version`) : 1, outputRoot: textValue(value.output_root, `${rootPath}.output_root`), scenes: listValue(value.scenes, `${rootPath}.scenes`).map((item, i) => parseScene(item, `${rootPath}.scenes[${i}]`)) }; }
function validatePaths(scenes: readonly UnifiedQaScene[], repositoryRoot: string): void { for (const scene of scenes) { for (const path of [scene.baseline.image, scene.baseline.stats, scene.baseline.metrics]) assertSafeRepositoryPath(path, `validation/baselines/${scene.target}`); if (scene.baseline.mask) assertSafeRepositoryPath(scene.baseline.mask, "validation/masks"); verifyOptionalSha256(resolve(repositoryRoot, scene.baseline.image), scene.baseline.sha256); } }
function parseLegacyMap(path: string): LegacyIdMapEntry[] { const root = objectValue(readYaml(path), path, ["legacy_id_map"]); return listValue(root.legacy_id_map, `${path}.legacy_id_map`).map((raw, i) => { const p = `${path}.legacy_id_map[${i}]`; const v = objectValue(raw, p, ["legacy", "canonical", "kind"]); const kind = textValue(v.kind, `${p}.kind`); if (!["scene", "probe", "timing", "counter", "informational"].includes(kind)) throw new Error(`${p}.kind is invalid`); return { legacy: identifier(v.legacy, `${p}.legacy`), canonical: identifier(v.canonical, `${p}.canonical`), kind: kind as LegacyIdMapEntry["kind"] }; }); }
function validateLegacyMap(entries: readonly LegacyIdMapEntry[], scenes: readonly UnifiedQaScene[]): void { assertUnique(entries.map((entry) => `${entry.kind}:${entry.legacy}`), "legacy QA ID mapping"); const canonical = new Set<string>(); for (const scene of scenes) { canonical.add(`scene:${scene.id}`); for (const p of scene.region_probes) canonical.add(`probe:${p.id}`); for (const g of scene.timing_gates) canonical.add(`timing:${g.id}`); for (const g of scene.counter_gates) canonical.add(`counter:${g.id}`); for (const m of scene.informational_metrics) canonical.add(`informational:${m.id}`); } for (const entry of entries) if (!canonical.has(`${entry.kind}:${entry.canonical}`)) throw new Error(`legacy mapping targets missing ID ${entry.kind}:${entry.canonical}`); }
function readYaml(path: string): unknown { try { return load(readFileSync(path, "utf8")); } catch (error) { throw new Error(`failed to parse ${path}: ${error instanceof Error ? error.message : error}`); } }
