import type { QaCounterGate, QaInformationalMetric, QaRegionProbe, UnifiedQaScene } from "./schema.js";
import { assertUnique } from "./validation.js";
import { booleanValue, finite, identifier, integer, laneValue, listValue, nonNegative, nonNegativeInteger, nullableText, objectValue, positive, positiveInteger, strings, targetValue, textValue, tuple, unit } from "./manifest_value.js";

const SCENE_KEYS = ["id", "target", "lane", "enabled", "tags", "launch", "settle", "capture", "baseline", "image_gates", "region_probes", "timing_gates", "counter_gates", "informational_metrics", "specialized_commands"] as const;

export function parseScene(raw: unknown, path: string): UnifiedQaScene {
  const value = objectValue(raw, path, SCENE_KEYS);
  const result: UnifiedQaScene = {
    id: identifier(value.id, `${path}.id`), target: targetValue(value.target, `${path}.target`), lane: laneValue(value.lane, `${path}.lane`), enabled: booleanValue(value.enabled, `${path}.enabled`), tags: strings(value.tags, `${path}.tags`),
    launch: parseLaunch(value.launch, `${path}.launch`), settle: parseSettle(value.settle, `${path}.settle`), capture: parseCapture(value.capture, `${path}.capture`), baseline: parseBaseline(value.baseline, `${path}.baseline`), image_gates: parseImageGates(value.image_gates, `${path}.image_gates`),
    region_probes: listValue(value.region_probes, `${path}.region_probes`).map((item, i) => parseProbe(item, `${path}.region_probes[${i}]`)),
    timing_gates: listValue(value.timing_gates, `${path}.timing_gates`).map((item, i) => parseTiming(item, `${path}.timing_gates[${i}]`)),
    counter_gates: listValue(value.counter_gates, `${path}.counter_gates`).map((item, i) => parseCounter(item, `${path}.counter_gates[${i}]`)),
    informational_metrics: listValue(value.informational_metrics, `${path}.informational_metrics`).map((item, i) => parseInfo(item, `${path}.informational_metrics[${i}]`)), specialized_commands: strings(value.specialized_commands, `${path}.specialized_commands`),
  };
  assertUnique(result.region_probes.map(({ id }) => id), `region probe id in scene ${result.id}`); assertUnique(result.timing_gates.map(({ id }) => id), `timing gate id in scene ${result.id}`); assertUnique(result.counter_gates.map(({ id }) => id), `counter gate id in scene ${result.id}`); assertUnique(result.informational_metrics.map(({ id }) => id), `informational metric id in scene ${result.id}`);
  return result;
}
function parseLaunch(raw: unknown, path: string): UnifiedQaScene["launch"] {
  const value = objectValue(raw, path, ["world_seed", "world_mode", "scene", "quality", "render_resolution_preset", "viewport", "device_pixel_ratio", "camera", "lighting", "weather", "flags"]); const camera = objectValue(value.camera, `${path}.camera`, ["position", "yaw_deg", "pitch_deg", "fov_y_deg"]); const lighting = objectValue(value.lighting, `${path}.lighting`, ["time_of_day_hours", "sun_elevation_deg", "sun_azimuth_deg"]); const weather = objectValue(value.weather, `${path}.weather`, ["wind_time_s", "cloud_time_s", "particle_time_s", "precipitation"]); const flags = objectValue(value.flags, `${path}.flags`);
  for (const [key, flag] of Object.entries(flags)) if (!["string", "number", "boolean"].includes(typeof flag)) throw new Error(`${path}.flags.${key} must be scalar`);
  return { world_seed: integer(value.world_seed, `${path}.world_seed`), world_mode: textValue(value.world_mode, `${path}.world_mode`), scene: textValue(value.scene, `${path}.scene`), quality: textValue(value.quality, `${path}.quality`), render_resolution_preset: textValue(value.render_resolution_preset, `${path}.render_resolution_preset`), viewport: tuple(value.viewport, 2, positiveInteger, `${path}.viewport`) as [number, number], device_pixel_ratio: positive(value.device_pixel_ratio, `${path}.device_pixel_ratio`), camera: { position: tuple(camera.position, 3, finite, `${path}.camera.position`) as [number, number, number], yaw_deg: finite(camera.yaw_deg, `${path}.camera.yaw_deg`), pitch_deg: finite(camera.pitch_deg, `${path}.camera.pitch_deg`), fov_y_deg: positive(camera.fov_y_deg, `${path}.camera.fov_y_deg`) }, lighting: { time_of_day_hours: finite(lighting.time_of_day_hours, `${path}.lighting.time_of_day_hours`), sun_elevation_deg: finite(lighting.sun_elevation_deg, `${path}.lighting.sun_elevation_deg`), sun_azimuth_deg: finite(lighting.sun_azimuth_deg, `${path}.lighting.sun_azimuth_deg`) }, weather: { wind_time_s: finite(weather.wind_time_s, `${path}.weather.wind_time_s`), cloud_time_s: finite(weather.cloud_time_s, `${path}.weather.cloud_time_s`), particle_time_s: finite(weather.particle_time_s, `${path}.weather.particle_time_s`), precipitation: textValue(weather.precipitation, `${path}.weather.precipitation`) }, flags: flags as Record<string, string | number | boolean> };
}
function parseSettle(raw: unknown, path: string): UnifiedQaScene["settle"] { const v = objectValue(raw, path, ["ready_timeout_ms", "warmup_frames", "settle_frames", "freeze_after_settle"]); return { ready_timeout_ms: positiveInteger(v.ready_timeout_ms, `${path}.ready_timeout_ms`), warmup_frames: nonNegativeInteger(v.warmup_frames, `${path}.warmup_frames`), settle_frames: nonNegativeInteger(v.settle_frames, `${path}.settle_frames`), freeze_after_settle: booleanValue(v.freeze_after_settle, `${path}.freeze_after_settle`) }; }
function parseCapture(raw: unknown, path: string): UnifiedQaScene["capture"] { const v = objectValue(raw, path, ["checkpoint", "image", "include_hud", "include_debug_overlays"]); return { checkpoint: textValue(v.checkpoint, `${path}.checkpoint`), image: textValue(v.image, `${path}.image`), include_hud: booleanValue(v.include_hud, `${path}.include_hud`), include_debug_overlays: booleanValue(v.include_debug_overlays, `${path}.include_debug_overlays`) }; }
function parseBaseline(raw: unknown, path: string): UnifiedQaScene["baseline"] { const v = objectValue(raw, path, ["image", "stats", "metrics", "mask", "sha256"]); return { image: textValue(v.image, `${path}.image`), stats: textValue(v.stats, `${path}.stats`), metrics: textValue(v.metrics, `${path}.metrics`), mask: nullableText(v.mask, `${path}.mask`), sha256: nullableText(v.sha256, `${path}.sha256`) }; }
function parseImageGates(raw: unknown, path: string): UnifiedQaScene["image_gates"] { const keys = ["required", "changed_pixel_threshold", "mean_absolute_error_max", "p95_absolute_error_max", "changed_pixel_fraction_max", "edge_error_mean_max", "luminance_mean_delta_max", "luminance_stddev_delta_max", "chroma_mean_delta_max"]; const v = objectValue(raw, path, keys); return { required: booleanValue(v.required, `${path}.required`), changed_pixel_threshold: unit(v.changed_pixel_threshold, `${path}.changed_pixel_threshold`), mean_absolute_error_max: nonNegative(v.mean_absolute_error_max, `${path}.mean_absolute_error_max`), p95_absolute_error_max: nonNegative(v.p95_absolute_error_max, `${path}.p95_absolute_error_max`), changed_pixel_fraction_max: unit(v.changed_pixel_fraction_max, `${path}.changed_pixel_fraction_max`), edge_error_mean_max: nonNegative(v.edge_error_mean_max, `${path}.edge_error_mean_max`), luminance_mean_delta_max: nonNegative(v.luminance_mean_delta_max, `${path}.luminance_mean_delta_max`), luminance_stddev_delta_max: nonNegative(v.luminance_stddev_delta_max, `${path}.luminance_stddev_delta_max`), chroma_mean_delta_max: nonNegative(v.chroma_mean_delta_max, `${path}.chroma_mean_delta_max`) }; }
function parseProbe(raw: unknown, path: string): QaRegionProbe { const v = objectValue(raw, path, ["id", "rect_normalized", "gates"]); const gates = objectValue(v.gates, `${path}.gates`, ["luminance_mean", "luminance_stddev", "chroma_mean", "black_pixel_fraction", "clipped_pixel_fraction", "edge_magnitude"], true); const range = (rawRange: unknown, p: string) => { if (rawRange === undefined) return undefined; const r = objectValue(rawRange, p, ["min", "max"], true); if (r.min === undefined && r.max === undefined) throw new Error(`${p} must define min or max`); return { ...(r.min === undefined ? {} : { min: finite(r.min, `${p}.min`) }), ...(r.max === undefined ? {} : { max: finite(r.max, `${p}.max`) }) }; }; const rect = tuple(v.rect_normalized, 4, unit, `${path}.rect_normalized`) as [number, number, number, number]; if (rect[2] <= 0 || rect[3] <= 0 || rect[0] + rect[2] > 1 || rect[1] + rect[3] > 1) throw new Error(`${path}.rect_normalized is invalid`); return { id: identifier(v.id, `${path}.id`), rect_normalized: rect, gates: { luminance_mean: range(gates.luminance_mean, `${path}.gates.luminance_mean`), luminance_stddev: range(gates.luminance_stddev, `${path}.gates.luminance_stddev`), chroma_mean: range(gates.chroma_mean, `${path}.gates.chroma_mean`), black_pixel_fraction: range(gates.black_pixel_fraction, `${path}.gates.black_pixel_fraction`), clipped_pixel_fraction: range(gates.clipped_pixel_fraction, `${path}.gates.clipped_pixel_fraction`), edge_magnitude: range(gates.edge_magnitude, `${path}.gates.edge_magnitude`) } }; }
function parseTiming(raw: unknown, path: string): UnifiedQaScene["timing_gates"][number] { const v = objectValue(raw, path, ["id", "metric", "max", "enforcement", "required"]); const enforcement = textValue(v.enforcement, `${path}.enforcement`); if (enforcement !== "required" && enforcement !== "advisory") throw new Error(`${path}.enforcement is invalid`); return { id: identifier(v.id, `${path}.id`), metric: textValue(v.metric, `${path}.metric`), max: positive(v.max, `${path}.max`), enforcement, required: booleanValue(v.required, `${path}.required`) }; }
function parseCounter(raw: unknown, path: string): QaCounterGate { const v = objectValue(raw, path, ["id", "key", "operator", "value", "range", "required"], true); const operator = textValue(v.operator, `${path}.operator`); if (!["equals", "min", "max", "between"].includes(operator)) throw new Error(`${path}.operator is invalid`); const base = { id: identifier(v.id, `${path}.id`), key: textValue(v.key, `${path}.key`), required: booleanValue(v.required, `${path}.required`) }; if (operator === "between") { if (v.value !== undefined) throw new Error(`${path}.value is forbidden for between`); return { ...base, operator, range: tuple(v.range, 2, finite, `${path}.range`) as [number, number] }; } if (v.range !== undefined) throw new Error(`${path}.range is only valid for between`); const expected = finite(v.value, `${path}.value`); if (operator === "min" && expected === 0) throw new Error(`${path} min: 0 must be informational`); return { ...base, operator: operator as "equals" | "min" | "max", value: expected }; }
function parseInfo(raw: unknown, path: string): QaInformationalMetric { const v = objectValue(raw, path, ["id", "key", "required"]); if (v.required !== false) throw new Error(`${path}.required must be false`); return { id: identifier(v.id, `${path}.id`), key: textValue(v.key, `${path}.key`), required: false }; }
